spring:
  security:
    jwt:
      key: abcdfghijk
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wca123...

